# Generated by Django 5.2.7 on 2025-11-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_thesis_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('CONCEPT_PAPER', 'Concept Paper'), ('RESEARCH_PROPOSAL', 'Research Proposal'), ('FINAL_MANUSCRIPT', 'Final Manuscript'), ('OTHER', 'Other Document')], default='OTHER', max_length=32),
        ),
    ]
