# Generated by Django 5.2.7 on 2025-11-23 03:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_document_document_type'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalSheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='pending', help_text='Approval decision', max_length=20)),
                ('comments', models.TextField(blank=True, help_text="Reviewer's comments")),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoScheduleRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the scheduling run', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detailed results and information about the scheduling run')),
                ('run_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the scheduling run was executed')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the scheduling run was completed', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Auto Schedule Run',
                'verbose_name_plural': 'Auto Schedule Runs',
                'ordering': ['-run_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_storage_id', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rubric_scores', models.JSONField(default=dict, help_text='Scores for each criterion in the evaluation rubric')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, help_text='Total score calculated from rubric', max_digits=5, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('pass', 'Pass'), ('pass_with_revision', 'Pass with Revisions'), ('fail', 'Fail'), ('conditional_pass', 'Conditional Pass')], help_text='Overall recommendation', max_length=20, null=True)),
                ('comments', models.TextField(blank=True, help_text='Detailed feedback')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_in_group', models.CharField(choices=[('member', 'Member'), ('secretary', 'Secretary'), ('treasurer', 'Treasurer')], default='member', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, help_text='Whether email notifications are enabled')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Whether in-app notifications are enabled')),
                ('push_enabled', models.BooleanField(default=False, help_text='Whether push notifications are enabled')),
                ('digest_enabled', models.BooleanField(default=True, help_text='Whether to receive digest emails for non-urgent notifications')),
                ('digest_frequency', models.PositiveSmallIntegerField(default=24, help_text='How often to send digest emails (in hours)')),
                ('last_digest_sent', models.DateTimeField(blank=True, help_text='When the last digest email was sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the preferences were created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the preferences were last updated')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for the template', max_length=100, unique=True)),
                ('notification_type', models.CharField(choices=[('thesis_submitted', 'Thesis Submitted'), ('defense_scheduled', 'Defense Scheduled'), ('defense_reminder', 'Defense Reminder'), ('defense_cancelled', 'Defense Cancelled'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_submitted', 'Evaluation Submitted'), ('thesis_approved', 'Thesis Approved'), ('thesis_rejected', 'Thesis Rejected'), ('new_comment', 'New Comment'), ('mention', 'Mention'), ('system_alert', 'System Alert'), ('other', 'Other')], help_text='Type of notification this template is for', max_length=50)),
                ('subject_template', models.CharField(help_text='Subject template (supports template variables)', max_length=255)),
                ('message_template', models.TextField(help_text='Message template (supports template variables and HTML)')),
                ('email_enabled', models.BooleanField(default=True, help_text='Whether this notification type can be sent via email')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Whether this notification type can be sent as an in-app notification')),
                ('push_enabled', models.BooleanField(default=False, help_text='Whether this notification type can be sent as a push notification')),
                ('default_priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Default priority for this notification type', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the template was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the template was last updated')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OralDefenseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Title for the defense session', max_length=255)),
                ('start', models.DateTimeField(help_text='Scheduled start time of the defense')),
                ('end', models.DateTimeField(help_text='Scheduled end time of the defense')),
                ('location', models.CharField(blank=True, help_text='Physical or virtual location', max_length=500)),
                ('meeting_url', models.URLField(blank=True, help_text='Meeting URL for virtual defenses')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the defense', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the defense')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Oral Defense Schedule',
                'verbose_name_plural': 'Oral Defense Schedules',
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='PanelMemberAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week')),
                ('start_time', models.TimeField(help_text='Start time of availability')),
                ('end_time', models.TimeField(help_text='End time of availability')),
                ('is_recurring', models.BooleanField(default=True, help_text='Whether this availability repeats weekly')),
                ('valid_from', models.DateField(blank=True, help_text='Start date of this availability (null means indefinitely)', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='End date of this availability (null means indefinitely)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Panel Member Availabilities',
                'ordering': ['user', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TopicProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField()),
                ('keywords', models.JSONField(default=list, help_text='List of keywords for the proposal')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_revision', 'Needs Revision')], default='draft', help_text='Current status of the topic proposal', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='defenseschedule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='defenseschedule',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='thesis',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Theses'},
        ),
        migrations.RenameField(
            model_name='document',
            old_name='google_doc_url',
            new_name='google_doc_edit_url',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='google_drive_embed_url',
            new_name='viewer_url',
        ),
        migrations.RemoveField(
            model_name='document',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='body',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='link',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='proposer',
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='doc_embed_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_storage_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='google_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_google_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, help_text='URL for the action associated with this notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the email notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the notification expires (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_sent',
            field=models.BooleanField(default=False, help_text='Whether an email notification was sent'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message',
            field=models.TextField(default='', help_text='Detailed message content'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('thesis_submitted', 'Thesis Submitted'), ('defense_scheduled', 'Defense Scheduled'), ('defense_reminder', 'Defense Reminder'), ('defense_cancelled', 'Defense Cancelled'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_submitted', 'Evaluation Submitted'), ('thesis_approved', 'Thesis Approved'), ('thesis_rejected', 'Thesis Rejected'), ('new_comment', 'New Comment'), ('mention', 'Mention'), ('system_alert', 'System Alert'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Additional data related to the notification'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Priority level of the notification', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, help_text='When the notification was marked as read', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(help_text='User who will receive the notification', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.UUIDField(blank=True, help_text='ID of the related object', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='User who triggered the notification (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When the notification was last updated'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='adviser',
            field=models.ForeignKey(help_text='Thesis adviser', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_theses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='thesis',
            name='archived_document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_in_thesis', to='api.document'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thesis',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('concept_paper', 'Concept Paper'), ('research_proposal', 'Research Proposal'), ('final_manuscript', 'Final Manuscript'), ('approval_sheet', 'Approval Sheet'), ('evaluation_form', 'Evaluation Form'), ('other', 'Other Document')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='thesis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.thesis'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the notification was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the notification has been read'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Brief title of the notification', max_length=255),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='adviser_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='api_notific_recipie_535048_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='api_notific_created_238c70_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='api_notific_notific_574e18_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority'], name='api_notific_priorit_c4e23f_idx'),
        ),
        migrations.AddField(
            model_name='approvalsheet',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Approval document if uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_sheets', to='api.document'),
        ),
        migrations.AddField(
            model_name='approvalsheet',
            name='panel_member',
            field=models.ForeignKey(help_text='Panel member who is approving', on_delete=django.db.models.deletion.CASCADE, related_name='approval_sheets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoschedulerun',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated the scheduling run (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_schedule_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='autoschedulerun',
            name='thesis',
            field=models.ForeignKey(help_text='Thesis associated with this scheduling run', on_delete=django.db.models.deletion.CASCADE, related_name='auto_schedule_runs', to='api.thesis'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.document'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Evaluation document if uploaded', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='api.document'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='evaluator',
            field=models.ForeignKey(help_text='Panel member who provided the evaluation', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='api.group'),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(help_text='User these preferences belong to', on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oraldefenseschedule',
            name='organizer',
            field=models.ForeignKey(help_text='User who scheduled this defense', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organized_defenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oraldefenseschedule',
            name='panel_members',
            field=models.ManyToManyField(blank=True, help_text='Panel members for this defense', related_name='panel_defenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='oraldefenseschedule',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oral_defense_schedules', to='api.thesis'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='api.oraldefenseschedule'),
        ),
        migrations.AddField(
            model_name='approvalsheet',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_sheets', to='api.oraldefenseschedule'),
        ),
        migrations.AddField(
            model_name='panelmemberavailability',
            name='user',
            field=models.ForeignKey(help_text='Panel member', on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topicproposal',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_proposals', to='api.group'),
        ),
        migrations.AddField(
            model_name='topicproposal',
            name='preferred_adviser',
            field=models.ForeignKey(help_text='Preferred adviser for this topic', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='topic_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.topicproposal'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='origin_proposal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resulting_thesis', to='api.topicproposal'),
        ),
        migrations.DeleteModel(
            name='DefenseSchedule',
        ),
        migrations.AddIndex(
            model_name='autoschedulerun',
            index=models.Index(fields=['thesis', 'status'], name='api_autosch_thesis__053348_idx'),
        ),
        migrations.AddIndex(
            model_name='autoschedulerun',
            index=models.Index(fields=['status'], name='api_autosch_status_ec045b_idx'),
        ),
        migrations.AddIndex(
            model_name='autoschedulerun',
            index=models.Index(fields=['run_at'], name='api_autosch_run_at_1f6ea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'user')},
        ),
        migrations.AddConstraint(
            model_name='oraldefenseschedule',
            constraint=models.CheckConstraint(check=models.Q(('start__lt', models.F('end'))), name='defense_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('schedule', 'evaluator')},
        ),
        migrations.AlterUniqueTogether(
            name='approvalsheet',
            unique_together={('schedule', 'panel_member')},
        ),
        migrations.AlterUniqueTogether(
            name='panelmemberavailability',
            unique_together={('user', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
