# Generated by Django 5.2.7 on 2025-11-23 03:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_group_members_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='google_doc_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='is_google_doc',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriveCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credential_type', models.CharField(choices=[('user', 'User OAuth'), ('service_account', 'Service Account')], default='user', help_text='Type of credentials', max_length=20)),
                ('token', models.JSONField(help_text='OAuth token or service account key')),
                ('refresh_token', models.CharField(blank=True, help_text='OAuth refresh token (if applicable)', max_length=500, null=True)),
                ('token_uri', models.URLField(blank=True, help_text='OAuth token URI (if applicable)')),
                ('client_id', models.CharField(blank=True, help_text='OAuth client ID (if applicable)', max_length=255)),
                ('client_secret', models.CharField(blank=True, help_text='OAuth client secret (if applicable)', max_length=255)),
                ('scopes', models.TextField(blank=True, help_text='Comma-separated list of OAuth scopes')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether these credentials are active')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When these credentials were last used', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User these credentials belong to', on_delete=django.db.models.deletion.CASCADE, related_name='drive_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drive Credential',
                'verbose_name_plural': 'Drive Credentials',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='api_drivecr_user_id_743026_idx'), models.Index(fields=['is_active'], name='api_drivecr_is_acti_745173_idx'), models.Index(fields=['expires_at'], name='api_drivecr_expires_b15ed7_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriveFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_id', models.CharField(help_text='Google Drive folder ID', max_length=255, unique=True)),
                ('name', models.CharField(help_text='Name of the folder', max_length=255)),
                ('folder_type', models.CharField(choices=[('thesis', 'Thesis'), ('group', 'Group'), ('submission', 'Submission'), ('archive', 'Archive'), ('other', 'Other')], help_text='Type of folder', max_length=20)),
                ('web_view_link', models.URLField(blank=True, help_text='URL to view the folder in Google Drive')),
                ('created_in_drive_at', models.DateTimeField(blank=True, help_text='When the folder was created in Google Drive', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, help_text='User who owns this folder', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_folders', to=settings.AUTH_USER_MODEL)),
                ('parent_folder', models.ForeignKey(blank=True, help_text='Parent folder (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfolders', to='api.drivefolder')),
            ],
            options={
                'verbose_name': 'Drive Folder',
                'verbose_name_plural': 'Drive Folders',
                'ordering': ['folder_type', 'name'],
                'indexes': [models.Index(fields=['folder_id'], name='api_drivefo_folder__6efdd7_idx'), models.Index(fields=['folder_type'], name='api_drivefo_folder__ae49e5_idx'), models.Index(fields=['owner'], name='api_drivefo_owner_i_c8a2b0_idx')],
            },
        ),
    ]
