# Generated by Django 5.2.7 on 2025-11-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_documentversion_google_doc_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('thesis_submitted', 'Thesis Submitted'), ('defense_scheduled', 'Defense Scheduled'), ('defense_reminder', 'Defense Reminder'), ('defense_cancelled', 'Defense Cancelled'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_submitted', 'Evaluation Submitted'), ('thesis_approved', 'Thesis Approved'), ('thesis_rejected', 'Thesis Rejected'), ('new_comment', 'New Comment'), ('mention', 'Mention'), ('system_alert', 'System Alert'), ('schedule_created', 'Schedule Created'), ('topic_proposal_reviewed', 'Topic Proposal Reviewed'), ('document_updated', 'Document Updated'), ('adviser_changed', 'Adviser Changed'), ('approval_sheet_submitted', 'Approval Sheet Submitted'), ('other', 'Other')], default='other', help_text='Type of notification', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('thesis_submitted', 'Thesis Submitted'), ('defense_scheduled', 'Defense Scheduled'), ('defense_reminder', 'Defense Reminder'), ('defense_cancelled', 'Defense Cancelled'), ('document_uploaded', 'Document Uploaded'), ('document_approved', 'Document Approved'), ('document_rejected', 'Document Rejected'), ('evaluation_submitted', 'Evaluation Submitted'), ('thesis_approved', 'Thesis Approved'), ('thesis_rejected', 'Thesis Rejected'), ('new_comment', 'New Comment'), ('mention', 'Mention'), ('system_alert', 'System Alert'), ('schedule_created', 'Schedule Created'), ('topic_proposal_reviewed', 'Topic Proposal Reviewed'), ('document_updated', 'Document Updated'), ('adviser_changed', 'Adviser Changed'), ('approval_sheet_submitted', 'Approval Sheet Submitted'), ('other', 'Other')], help_text='Type of notification this template is for', max_length=50),
        ),
    ]
