# Generated by Django 5.2.7 on 2025-11-23 03:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_notification_notification_type_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('permission_denied', 'Permission Denied'), ('other', 'Other')], help_text='Type of action performed', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string of the browser/device')),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the related object', null=True)),
                ('old_values', models.JSONField(blank=True, help_text='Values before the change (for updates/deletes)', null=True)),
                ('new_values', models.JSONField(blank=True, help_text='Values after the change (for creates/updates)', null=True)),
                ('request_path', models.CharField(blank=True, help_text='Request path/URL', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, help_text='HTTP status code of the response', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the action was performed')),
                ('content_type', models.ForeignKey(blank=True, help_text='Content type of the related object', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['user'], name='api_auditlo_user_id_b0c441_idx'), models.Index(fields=['content_type', 'object_id'], name='api_auditlo_content_3674ae_idx'), models.Index(fields=['created_at'], name='api_auditlo_created_ec4a64_idx')],
            },
        ),
    ]
