# Generated by Django 5.2.8 on 2025-11-23 04:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_type', models.CharField(choices=[('thesis', 'Thesis'), ('document', 'Document'), ('evaluation', 'Evaluation'), ('group', 'Group'), ('user', 'User'), ('other', 'Other')], help_text='Type of content being archived', max_length=20)),
                ('original_id', models.UUIDField(help_text='Original ID of the archived item')),
                ('data', models.JSONField(help_text='JSON representation of the archived data')),
                ('reason', models.TextField(blank=True, help_text='Reason for archiving')),
                ('retention_period_years', models.PositiveSmallIntegerField(default=7, help_text='Number of years to retain this record')),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the record was archived')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this archive record expires (auto-calculated)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_by', models.ForeignKey(help_text='User who performed the archival', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archive Record',
                'verbose_name_plural': 'Archive Records',
                'ordering': ['-archived_at'],
                'indexes': [models.Index(fields=['content_type', 'original_id'], name='api_archive_content_b8f3b7_idx'), models.Index(fields=['archived_at'], name='api_archive_archive_081d2f_idx'), models.Index(fields=['expires_at'], name='api_archive_expires_bd3d79_idx')],
            },
        ),
    ]
