# Generated by Django 5.0 on 2025-11-24 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='possible_topics',
            field=models.TextField(blank=True, help_text='Possible research topics, one per line'),
        ),
    ]
