# Generated by Django 5.0 on 2025-11-24 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_group_possible_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='group',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='group',
            name='proposed_topic_title',
        ),
    ]
