# Generated by Django 5.0 on 2025-11-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_group_abstract_remove_group_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='role_in_group',
            field=models.CharField(choices=[('member', 'Member'), ('leader', 'Leader')], default='member', max_length=20),
        ),
    ]
