# Generated by Django 4.2.16 on 2025-11-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_groupmember_role_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='preferred_adviser_id',
            field=models.CharField(blank=True, help_text='Preferred adviser ID from group proposal', max_length=36, null=True),
        ),
    ]
