# Generated by Django 5.0 on 2025-11-27 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_group_preferred_adviser_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='proposer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_theses', to=settings.AUTH_USER_MODEL),
        ),
    ]
