# Generated by Django 5.0 on 2025-11-29 10:30

from django.db import migrations

def set_thesis_adviser_from_group(apps, schema_editor):
    """
    Set the adviser field for existing theses based on their group's adviser.
    """
    Thesis = apps.get_model('api', 'Thesis')
    Group = apps.get_model('api', 'Group')
    
    # Update all theses that don't have an adviser set
    for thesis in Thesis.objects.filter(adviser__isnull=True):
        if thesis.group and thesis.group.adviser:
            thesis.adviser = thesis.group.adviser
            thesis.save(update_fields=['adviser'])

def reverse_set_thesis_adviser_from_group(apps, schema_editor):
    """
    Reverse function - set adviser to null for all theses.
    """
    Thesis = apps.get_model('api', 'Thesis')
    Thesis.objects.update(adviser=None)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_update_thesis_status_choices'),
    ]

    operations = [
        migrations.RunPython(set_thesis_adviser_from_group, reverse_set_thesis_adviser_from_group),
    ]
