# Generated by Django 5.0 on 2025-11-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_set_thesis_adviser_from_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='provider',
            field=models.CharField(choices=[('local', 'Local Storage'), ('drive', 'Google Drive'), ('google', 'Google Docs')], default='local', max_length=10),
        ),
    ]
