# Generated by Django 5.2.7 on 2025-11-30 10:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_fix_duplicate_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
