# Generated by Django 5.2.7 on 2025-11-30 15:30
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('concept_paper', 'Concept Paper'), ('research_proposal', 'Research Proposal'), ('final_manuscript', 'Final Manuscript'), ('approval_sheet', 'Approval Sheet'), ('evaluation_form', 'Evaluation Form')], default='concept_paper', max_length=32),
        ),
    ]
