# Generated by Django 5.2.7 on 2025-11-30 15:35
from django.db import migrations


def update_other_documents(apps, schema_editor):
    """
    Update all documents with document_type='other' to 'concept_paper'
    """
    Document = apps.get_model('api', 'Document')
    # Update all documents with 'other' type to 'concept_paper'
    Document.objects.filter(document_type='other').update(document_type='concept_paper')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_other_document_type'),
    ]

    operations = [
        migrations.RunPython(update_other_documents),
    ]
