# Generated by Django 5.2.7 on 2025-12-01 10:00

from django.db import migrations
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_document_status'),
    ]

    operations = [
        # Ensure all DriveCredential fields are properly set up
        migrations.AlterField(
            model_name='drivecredential',
            name='credential_type',
            field=models.CharField(choices=[('user', 'User OAuth')], default='user', help_text='Type of credentials', max_length=20),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='token',
            field=models.JSONField(help_text='OAuth token'),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='refresh_token',
            field=models.CharField(blank=True, help_text='OAuth refresh token (if applicable)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='token_uri',
            field=models.URLField(blank=True, help_text='OAuth token URI (if applicable)'),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='client_id',
            field=models.CharField(blank=True, help_text='OAuth client ID (if applicable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='client_secret',
            field=models.CharField(blank=True, help_text='OAuth client secret (if applicable)', max_length=255),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='scopes',
            field=models.TextField(blank=True, help_text='Comma-separated list of OAuth scopes'),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When the access token expires', null=True),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether these credentials are active'),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='last_used_at',
            field=models.DateTimeField(blank=True, help_text='When these credentials were last used', null=True),
        ),
        migrations.AlterField(
            model_name='drivecredential',
            name='user',
            field=models.OneToOneField(help_text='User these credentials belong to', on_delete=django.db.models.deletion.CASCADE, related_name='drive_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
