# Generated by Django 5.0 on 2025-12-05 14:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_update_drive_credentials_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('TOPIC_SUBMITTED', 'Topic Submitted'), ('TOPIC_APPROVED', 'Topic Approved'), ('TOPIC_REJECTED', 'Topic Rejected'), ('CONCEPT_SUBMITTED', 'Concept Submitted'), ('READY_FOR_CONCEPT_DEFENSE', 'Ready for Concept Defense'), ('CONCEPT_SCHEDULED', 'Concept Scheduled'), ('CONCEPT_APPROVED', 'Concept Approved'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('READY_FOR_PROPOSAL_DEFENSE', 'Ready for Proposal Defense'), ('PROPOSAL_SCHEDULED', 'Proposal Scheduled'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('RESEARCH_IN_PROGRESS', 'Research In Progress'), ('FINAL_SUBMITTED', 'Final Submitted'), ('READY_FOR_FINAL_DEFENSE', 'Ready for Final Defense'), ('FINAL_SCHEDULED', 'Final Scheduled'), ('FINAL_APPROVED', 'Final Approved'), ('REVISIONS_REQUIRED', 'Revisions Required'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='TOPIC_SUBMITTED', max_length=32),
        ),
        migrations.CreateModel(
            name='PanelAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('needs_revision', 'Needs Revision'), ('rejected', 'Rejected')], max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('panel_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_actions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panel_actions', to='api.oraldefenseschedule')),
            ],
            options={
                'verbose_name': 'Panel Action',
                'verbose_name_plural': 'Panel Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
