# Generated by Django 5.0 on 2025-12-06 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='deleted_at',
        ),
    ]
