# Generated by Django 5.0 on 2025-12-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_remove_thesis_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thesis',
            name='status',
            field=models.CharField(choices=[('TOPIC_SUBMITTED', 'Topic Submitted'), ('TOPIC_APPROVED', 'Topic Approved'), ('TOPIC_REJECTED', 'Topic Rejected'), ('CONCEPT_SUBMITTED', 'Concept Submitted'), ('READY_FOR_CONCEPT_DEFENSE', 'Ready for Concept Defense'), ('CONCEPT_SCHEDULED', 'Concept Scheduled'), ('CONCEPT_APPROVED', 'Concept Approved'), ('PROPOSAL_SUBMITTED', 'Proposal Submitted'), ('READY_FOR_PROPOSAL_DEFENSE', 'Ready for Proposal Defense'), ('PROPOSAL_SCHEDULED', 'Proposal Scheduled'), ('PROPOSAL_APPROVED', 'Proposal Approved'), ('RESEARCH_IN_PROGRESS', 'Research In Progress'), ('FINAL_SUBMITTED', 'Final Submitted'), ('READY_FOR_FINAL_DEFENSE', 'Ready for Final Defense'), ('FINAL_SCHEDULED', 'Final Scheduled'), ('FINAL_APPROVED', 'Final Approved'), ('CONCEPT_REVISIONS_REQUIRED', 'Concept Revisions Required'), ('PROPOSAL_REVISIONS_REQUIRED', 'Proposal Revisions Required'), ('FINAL_REVISIONS_REQUIRED', 'Final Revisions Required'), ('REVISIONS_REQUIRED', 'Revisions Required'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], default='TOPIC_SUBMITTED', max_length=32),
        ),
    ]
