# Generated by Django 5.0 on 2025-12-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_user_avatar_user_bio'),
        ('api', '0042_alter_thesis_status'),
    ]

    operations = [
    ]