# Generated by Django 5.0 on 2025-12-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_merge_0038_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oraldefenseschedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', help_text='Current status of the defense', max_length=20),
        ),
        migrations.DeleteModel(
            name='AutoScheduleRun',
        ),
    ]
