# Generated by Django 5.0 on 2025-12-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_oraldefenseschedule_status_and_more'),
    ]

    operations = [
        # First, remove the foreign key relationships before deleting the models
        migrations.RemoveField(
            model_name='thesis',
            name='origin_proposal',
        ),
        migrations.RemoveField(
            model_name='document',
            name='topic_proposal',
        ),
    ]