# Generated by Django 5.0 on 2025-12-11 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_remove_topic_proposal_dependencies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopicProposal',
        ),
        migrations.DeleteModel(
            name='PanelMemberAvailability',
        ),
    ]